artichoke/playground

.circleci/config.yml
Update build to use release mode.
=> Deploy playground to gh-pages branch

README.md
=> Link to artichoke.run

yarn.lock
Pull in fix for eslint-utils vuln.
=> Update JS deps with yarn upgrade

src/index.html
Add OpenGraph metadata for social sharing.
Fixes #9
=> Add OpenGraph metadata to HTML

src/index.html
=> Use png logo in og:image property

.eslintignore, .prettierignore, .rubocop.yml, scripts/format-text.sh, scripts/lint.sh
=> Fixup linter scripts to work with new toolchain

.circleci/config.yml, package.json, yarn.lock
@artichoke-ci is a machine user that has push access.
=> Build gh-pages branch with a machine user

.circleci/config.yml, assets/CNAME
This was accidentally removed in GH-35.
=> Add missing webpack step to deploy job

package.json, yarn.lock
=> Prune unused JS deps

Cargo.lock
cargo update
No manual breaking change upgrades.
=> Update Rust deps

.github/workflows/ci.yaml, .prettierignore, Rakefile, package.json, src/index.html, src/main.js, webpack.config.js, yarn.lock
- Remove unneeded prettier plugins
- Remove unneeded eslint plugins
- Invoke prettier in rake and CI with npx
- Remove invalid rake tasks (the Rakefile was cargo-culted from artichoke/artichoke)
- Remove prettier/eslint integration
- Remove babel eslint parser
- Upgrade to prettier 2
=> Remove some build infrastructure

src/index.html, src/partials/google-analytics.html
- Extract google analytics to partial
- Use favicons partial for mobile support
- Fix logo URL for og:image
=> Use extra partials

.rubocop.yml, Gemfile.lock
GH-66 introduces a warning.
This PR does the bump and adds the missing config.
=> Bump rubocop

Rakefile, package-lock.json, package.json
=> Rebuild js deps dependency lock from scratch

.github/labels.json, .github/workflows/repo-labels.yaml
sourced from boba and intaglio
=> Add repo labels, managed by souce control and CI

src/partials/nav.html
https://prettier.io/blog/2020/08/24/2.1.0.html#html
=> Update HTML formatting for prettier 2.1

.github/workflows/block-merge.yaml
See artichoke/project-infrastructure#44.
=> Block WIP or unmergeable PRs

package-lock.json
security fix for CVE-2020-7720
=> Regenerate lockfile to pull in node-forge 0.10.0

.github/workflows/playground.yaml
Pull in fix for CVE-2020-15228.
=> Bump setup-emsdk to v7

.github/workflows/playground.yaml
This mismatch was introduced in #229.
=> Sync RUSTFLAGS from package.json to playground.yaml GitHub Actions workflow

.github/workflows/audit.yaml, Cargo.lock, deny.toml, playground/Cargo.toml
Fixes #79 using a similar config to artichoke/artichoke.
=> Add cargo-deny config and audit CI job
